-- MySQL Script generated by MySQL Workbench
-- Sun Feb 15 23:42:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema erp_node
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp_node
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erp_node` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `erp_node` ;

-- -----------------------------------------------------
-- Table `erp_node`.`almacenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`almacenes` (
  `Id_Almacen` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Direccion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Almacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`periodos` (
  `Id_Periodo` INT NOT NULL AUTO_INCREMENT,
  `Año` INT NOT NULL,
  `Mes` INT NOT NULL,
  PRIMARY KEY (`Id_Periodo`),
  UNIQUE INDEX `Año` (`Año` ASC, `Mes` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`asientos` (
  `Id_Asiento` INT NOT NULL AUTO_INCREMENT,
  `Id_Periodo` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Glosa` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Asiento`),
  INDEX `Id_Periodo` (`Id_Periodo` ASC) VISIBLE,
  CONSTRAINT `asientos_ibfk_1`
    FOREIGN KEY (`Id_Periodo`)
    REFERENCES `erp_node`.`periodos` (`Id_Periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`cuenta_contable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`cuenta_contable` (
  `Id_Cuenta` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(20) NOT NULL,
  `Nombre_Cuenta` VARCHAR(150) NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_Cuenta`),
  UNIQUE INDEX `Codigo` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`asiento_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`asiento_detalle` (
  `Id_Detalle` INT NOT NULL AUTO_INCREMENT,
  `Id_Asiento` INT NOT NULL,
  `Id_Cuenta` INT NOT NULL,
  `Debe` DECIMAL(15,2) NULL DEFAULT '0.00',
  `Haber` DECIMAL(15,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`Id_Detalle`),
  INDEX `Id_Asiento` (`Id_Asiento` ASC) VISIBLE,
  INDEX `idx_cuenta` (`Id_Cuenta` ASC) VISIBLE,
  CONSTRAINT `asiento_detalle_ibfk_1`
    FOREIGN KEY (`Id_Asiento`)
    REFERENCES `erp_node`.`asientos` (`Id_Asiento`)
    ON DELETE CASCADE,
  CONSTRAINT `asiento_detalle_ibfk_2`
    FOREIGN KEY (`Id_Cuenta`)
    REFERENCES `erp_node`.`cuenta_contable` (`Id_Cuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`empleados` (
  `Id_Empleado` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Correo` VARCHAR(150) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Fecha_Ingreso` DATE NOT NULL,
  `Estado` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`Id_Empleado`),
  UNIQUE INDEX `DNI` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `Correo` (`Correo` ASC) VISIBLE,
  INDEX `idx_empleado_estado` (`Estado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`clientes` (
  `Id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Documento` VARCHAR(20) NULL DEFAULT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Correo` VARCHAR(150) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`proyectos` (
  `Id_Proyecto` INT NOT NULL AUTO_INCREMENT,
  `Id_Cliente` INT NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Fecha_Inicio` DATE NULL DEFAULT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  `Estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Proyecto`),
  INDEX `Id_Cliente` (`Id_Cliente` ASC) VISIBLE,
  CONSTRAINT `proyectos_ibfk_1`
    FOREIGN KEY (`Id_Cliente`)
    REFERENCES `erp_node`.`clientes` (`Id_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`asignaciones` (
  `Id_Asignacion` INT NOT NULL AUTO_INCREMENT,
  `Id_Empleado` INT NOT NULL,
  `Id_Proyecto` INT NOT NULL,
  `Horas_Asignadas` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Asignacion`),
  INDEX `Id_Empleado` (`Id_Empleado` ASC) VISIBLE,
  INDEX `Id_Proyecto` (`Id_Proyecto` ASC) VISIBLE,
  CONSTRAINT `asignaciones_ibfk_1`
    FOREIGN KEY (`Id_Empleado`)
    REFERENCES `erp_node`.`empleados` (`Id_Empleado`),
  CONSTRAINT `asignaciones_ibfk_2`
    FOREIGN KEY (`Id_Proyecto`)
    REFERENCES `erp_node`.`proyectos` (`Id_Proyecto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`categorias` (
  `Id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id_Categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`puestos` (
  `Id_Puesto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Puesto` VARCHAR(150) NOT NULL,
  `Salario_Base` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`Id_Puesto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`contratos` (
  `Id_Contrato` INT NOT NULL AUTO_INCREMENT,
  `Id_Empleado` INT NOT NULL,
  `Id_Puesto` INT NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Fin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Contrato`),
  INDEX `Id_Empleado` (`Id_Empleado` ASC) VISIBLE,
  INDEX `Id_Puesto` (`Id_Puesto` ASC) VISIBLE,
  CONSTRAINT `contratos_ibfk_1`
    FOREIGN KEY (`Id_Empleado`)
    REFERENCES `erp_node`.`empleados` (`Id_Empleado`),
  CONSTRAINT `contratos_ibfk_2`
    FOREIGN KEY (`Id_Puesto`)
    REFERENCES `erp_node`.`puestos` (`Id_Puesto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`ordenes` (
  `Id_Orden` INT NOT NULL AUTO_INCREMENT,
  `Id_Cliente` INT NOT NULL,
  `Fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Orden`),
  INDEX `Id_Cliente` (`Id_Cliente` ASC) VISIBLE,
  INDEX `idx_fecha` (`Fecha` ASC) VISIBLE,
  CONSTRAINT `ordenes_ibfk_1`
    FOREIGN KEY (`Id_Cliente`)
    REFERENCES `erp_node`.`clientes` (`Id_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`proveedores` (
  `Id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `RUC` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Proveedor`),
  UNIQUE INDEX `RUC` (`RUC` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`productos` (
  `Id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(150) NOT NULL,
  `Precio_Compra` DECIMAL(15,2) NULL DEFAULT NULL,
  `Precio_Venta` DECIMAL(15,2) NULL DEFAULT NULL,
  `Id_Categoria` INT NOT NULL,
  `Id_Proveedor` INT NOT NULL,
  PRIMARY KEY (`Id_Producto`),
  UNIQUE INDEX `Codigo` (`Codigo` ASC) VISIBLE,
  INDEX `Id_Categoria` (`Id_Categoria` ASC) VISIBLE,
  INDEX `Id_Proveedor` (`Id_Proveedor` ASC) VISIBLE,
  INDEX `idx_producto_nombre` (`Nombre` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`Id_Categoria`)
    REFERENCES `erp_node`.`categorias` (`Id_Categoria`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `erp_node`.`proveedores` (`Id_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`detalle_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`detalle_orden` (
  `Id_Detalle` INT NOT NULL AUTO_INCREMENT,
  `Id_Orden` INT NOT NULL,
  `Id_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`Id_Detalle`),
  INDEX `Id_Orden` (`Id_Orden` ASC) VISIBLE,
  INDEX `Id_Producto` (`Id_Producto` ASC) VISIBLE,
  CONSTRAINT `detalle_orden_ibfk_1`
    FOREIGN KEY (`Id_Orden`)
    REFERENCES `erp_node`.`ordenes` (`Id_Orden`)
    ON DELETE CASCADE,
  CONSTRAINT `detalle_orden_ibfk_2`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `erp_node`.`productos` (`Id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`ordenes_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`ordenes_compra` (
  `Id_Orden_Compra` INT NOT NULL AUTO_INCREMENT,
  `Id_Proveedor` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Orden_Compra`),
  INDEX `Id_Proveedor` (`Id_Proveedor` ASC) VISIBLE,
  CONSTRAINT `ordenes_compra_ibfk_1`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `erp_node`.`proveedores` (`Id_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`detalle_orden_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`detalle_orden_compra` (
  `Id_Detalle` INT NOT NULL AUTO_INCREMENT,
  `Id_Orden_Compra` INT NOT NULL,
  `Id_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Costo` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Detalle`),
  INDEX `Id_Orden_Compra` (`Id_Orden_Compra` ASC) VISIBLE,
  INDEX `Id_Producto` (`Id_Producto` ASC) VISIBLE,
  CONSTRAINT `detalle_orden_compra_ibfk_1`
    FOREIGN KEY (`Id_Orden_Compra`)
    REFERENCES `erp_node`.`ordenes_compra` (`Id_Orden_Compra`)
    ON DELETE CASCADE,
  CONSTRAINT `detalle_orden_compra_ibfk_2`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `erp_node`.`productos` (`Id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`facturas` (
  `Id_Factura` INT NOT NULL AUTO_INCREMENT,
  `Id_Orden` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Total` DECIMAL(15,2) NULL DEFAULT NULL,
  `Estado_Pago` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Factura`),
  INDEX `Id_Orden` (`Id_Orden` ASC) VISIBLE,
  CONSTRAINT `facturas_ibfk_1`
    FOREIGN KEY (`Id_Orden`)
    REFERENCES `erp_node`.`ordenes` (`Id_Orden`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`inventario` (
  `Id_Producto` INT NOT NULL,
  `Id_Almacen` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Stock_Minimo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Producto`, `Id_Almacen`),
  INDEX `Id_Almacen` (`Id_Almacen` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `erp_node`.`productos` (`Id_Producto`)
    ON DELETE CASCADE,
  CONSTRAINT `inventario_ibfk_2`
    FOREIGN KEY (`Id_Almacen`)
    REFERENCES `erp_node`.`almacenes` (`Id_Almacen`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`nominas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`nominas` (
  `Id_Nomina` INT NOT NULL AUTO_INCREMENT,
  `Id_Empleado` INT NOT NULL,
  `Id_Periodo` INT NOT NULL,
  `Total_Bruto` DECIMAL(15,2) NULL DEFAULT NULL,
  `Total_Deducciones` DECIMAL(15,2) NULL DEFAULT NULL,
  `Neto_Pagar` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Nomina`),
  INDEX `Id_Empleado` (`Id_Empleado` ASC) VISIBLE,
  INDEX `Id_Periodo` (`Id_Periodo` ASC) VISIBLE,
  CONSTRAINT `nominas_ibfk_1`
    FOREIGN KEY (`Id_Empleado`)
    REFERENCES `erp_node`.`empleados` (`Id_Empleado`),
  CONSTRAINT `nominas_ibfk_2`
    FOREIGN KEY (`Id_Periodo`)
    REFERENCES `erp_node`.`periodos` (`Id_Periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `erp_node`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp_node`.`pagos` (
  `Id_Pago` INT NOT NULL AUTO_INCREMENT,
  `Id_Factura` INT NOT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Monto` DECIMAL(15,2) NULL DEFAULT NULL,
  `Metodo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Pago`),
  INDEX `Id_Factura` (`Id_Factura` ASC) VISIBLE,
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`Id_Factura`)
    REFERENCES `erp_node`.`facturas` (`Id_Factura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
